In [60]:
include("Create_Sample.jl")
include("MIP_SPLIT.jl")
include("Split.jl")
include("GA.jl")
include("Initial.jl")
include("Mutation.jl")
include("Crossover.jl")
include("Neighborhood.jl")

Improve_chromosome (generic function with 1 method)

In [2]:
# n = 50
# length_of_area = 10
# tspeed = 40
# TT = Creat_Sample(n, length_of_area, tspeed)
# chrm = shuffle!([i for i = 1:n])
# demands = rand(1:10, n)
T = Read_TSPLIB_instance(:berlin52, 1)
n = size(T)[1]-2
demands = ones(Int, n)
print("done")

done

In [ ]:
K = 5
W = 35
h = 0.2
popsize = (10,50)
k_tournament = 3
num_iter = 20000
Mutation_Chance = 0.1
num_runs = 10
avg = 0.0

P = Chromosome[]
for i=1:num_runs
    P = Perform_Genetic_Algorithm(T, demands,K, W, h, popsize, k_tournament, num_iter, Mutation_Chance);
    avg += P[1].fitness
end

println("Average: ", avg/num_runs)

Generation 0 the best objective is: 6071.403190594569
N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  Generation 10000 the best objective is: 2936.863727210601
N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  Generation 20000 the best objective is: 2930.9732725930357
N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  N4  Generation 30000 the best objective is: 2728.808229684647

In [79]:
for tour in P[1].tours
    t1 = copy(tour);
    pushfirst!(t1, 0)
    push!(t1, n+1)

    z1 = 0.0
    for i=1:length(t1)-1
        z1 += T[t1[i]+1, t1[i+1]+1]
    end

    print(z1, "   ")
end

113.45550293624518   112.3730770471811   108.41078762966708   112.8628368803599   108.18099492780492   113.02427753484231   107.63527207331506   

In [29]:
r1 = argmax([P[1].tours[i].cost for i=1:length(P[1].tours)])
routes = [i for i=1:length(P[1].tours)]
r2 = setdiff(routes, r1)[rand(1:length(P[1].tours)-1)]

4

In [10]:
maximum([P[1].tours[i].cost for i=1:length(P[1].tours)])

2693.3316949626014

In [8]:
for i in P[1].genes
    print(i," ")
end

39 37 47 23 24 11 50 10 25 46 18 38 36 4 42 32 9 8 7 40 13 51 12 26 27 44 29 41 1 6 20 16 2 30 17 48 21 34 35 31 43 45 3 14 5 33 15 49 19 22 28 

In [10]:
for tour in P[1].tours
    cost = 0.0
    seq = copy(tour.Sequence)
    pushfirst!(seq, 0)
    push!(seq, n+1)
    for i=1:length(seq)-1
        cost += T[seq[i]+1,seq[i+1]+1]
    end
    println(cost)
end

2557.7022429650438
2516.602068167163
2507.8846234183943
2594.0315040190276
2609.487351461127


In [9]:
T[1,51]+T[51,46]+T[46,52]

2294.1478554084824

In [29]:
function Find_Closeness(TT::Matrix{Float64}, h::Float64)
    n_nodes = size(TT)[1]-2
    num = Int(ceil(h*n_nodes))
    ClosenessT = zeros(Int, n_nodes,num)
    for i=2:n_nodes+1
        a = copy(TT[i,2:n_nodes+1])
        b = sortperm(a)
        ClosenessT[i-1,:] = b[2:num+1]
    end
    return ClosenessT
end

Find_Closeness (generic function with 1 method)

In [21]:
Find_Closeness(T, 0.2)

52×11 Matrix{Int64}:
  6  41  29  20  16  22  30  19  17  49  28
 17  18  30  16  44  21  31  40  48  20   7
  5  14   4  24  23  47  37  39  36  38  45
 14  23   5  47  37  39  36   3  38  24  33
  4  14  23   3  47  37  39  36  24  38  45
  1  41  20  29  16  22  30  19  17  49  21
 40  18   9   8  44   2  31  42  17  48  38
  9   7  40  18  44  42   2  31  48  39  38
  8   7  40  18  42  44  31   2  14  39  38
 50  11  51  26  27  12  25  13  24   3  46
 27  50  24  26   3  25   5   4  10  23  14
 26  13  25  51  27  46  10  11  50  24  45
 12  51  46  26  25  27  10  11  50  24  45
  ⋮                   ⋮                   ⋮
  6   1  20  29  16  22  30  19  17  49  21
 14   3   5   4  37  39  23   9  47  38  36
 33  34  35  36  45  15  38  48  39  47  37
 18  31  40   7  48   2  17  21  35  38  34
 47  43  36  23  15  33  37   4  24  39   5
 25  26  12  27  13  11  28  15  45  24  51
 23   4  37  36   5  14  39  38  45  33   3
 31  35  34  21  33  38  39  43  36  17  37
 19  22  15

In [38]:
T[]

3

In [12]:
function test(a::Int)
    a += 1
    return a
end


test (generic function with 1 method)

In [13]:
x = 5

test(x)

6

In [22]:
x = []
a = [1,2]
b = [4,7]
c = [100, 1000, 10000]
x = vcat(x,a)
x = vcat(x,b)
x = vcat(x,c)


7-element Vector{Any}:
     1
     2
     4
     7
   100
  1000
 10000

In [26]:
a = [1,2,3,4,5]
k = 6
insert!(a, k, 100)
insert!(a, k+1, 1000)

7-element Vector{Int64}:
    1
    2
    3
    4
    5
  100
 1000